version: '3.4'

services:
  db:
    image: ${POSTGRES_IMAGE}
    ports:
      - "${DB_BIND_ADDRESS}:${DB_PORT}"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z ${DB_HEALTHCHECK_HOST} ${DB_HEALTHCHECK_PORT} || exit 1"]
      interval: ${DB_HEALTHCHECK_INTERVAL}
      timeout: ${DB_HEALTHCHECK_TIMEOUT}
      retries: ${DB_HEALTHCHECK_RETRIES}
    volumes:
      - db:/var/lib/postgresql/data

  app: &app_base
    image: ${FOREMAN_IMAGE}
    build:
      context: .
    command: ${APP_COMMAND}
    links:
      - db
      - redis-cache
      - redis-tasks
    ports:
      - "${APP_BIND_ADDRESS}:${APP_HTTP_PORT}"
      - "${APP_BIND_ADDRESS}:${APP_SSH_START}-${APP_SSH_END}"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 ${APP_HTTP_PORT} || exit 1"]
      interval: ${APP_HEALTHCHECK_INTERVAL}
      start_period: ${APP_HEALTHCHECK_START_PERIOD}

  orchestrator:
    <<: *app_base
    command: ${ORCHESTRATOR_COMMAND}
    
  worker:
    <<: *app_base
    command: ${WORKER_COMMAND}

  redis-cache:
    image: ${REDIS_CACHE_IMAGE}

  redis-tasks:
    image: ${REDIS_TASKS_IMAGE}
    command: ${REDIS_TASKS_COMMAND}
    volumes:
      - redis-persistent:/data

volumes:
  db:
  redis-persistent:
